# Generated by Django 3.0.2 on 2020-02-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos')),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('types', models.CharField(choices=[('gates', 'gates'), ('CCTV', 'CCTV'), ('Flood Lights', 'Flood Lights')], max_length=120)),
                ('datepost', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-datepost'],
            },
        ),
    ]
