# Generated by Django 3.0.2 on 2020-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(),
        ),
    ]
