# Generated by Django 3.0.2 on 2020-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_auto_20200214_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AlterField(
            model_name='items',
            name='types',
            field=models.CharField(choices=[('sliding gates', 'sliding gates'), ('swinging gates', 'swinging gates'), ('garage gates', 'garage gates'), ('CCTV', 'CCTV'), ('Flood Lights', 'Flood Lights')], max_length=120),
        ),
    ]
