# Generated by Django 3.1.1 on 2020-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0003_auto_20200216_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='title',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(help_text='200px by 200 px', upload_to='photos'),
        ),
    ]
