# Generated by Django 3.1.1 on 2020-11-20 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0004_auto_20201104_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(help_text='min:dimension 250px by 250 px', upload_to='photos'),
        ),
    ]
