# Generated by Django 3.1.1 on 2020-11-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0005_auto_20201120_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
