# Generated by Django 3.1.1 on 2020-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0006_auto_20201120_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='types',
            field=models.CharField(choices=[('sliding-gates', 'sliding gates'), ('swinging-gates', 'swinging gates'), ('garage-gates', 'garage gates'), ('CCTV', 'CCTV'), ('Flood-Lights', 'Flood Lights')], max_length=120),
        ),
    ]
